name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # Adjust branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 2c2eae7c46fdef478ca007471a296695  # Replace with your Cloudflare account ID
          projectName: demo  # Replace with your Cloudflare project name
          directory: dist  # Replace with your build output directory
