name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # Adjust branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/github-script@0.6.0
        with:
          script: |
            const { execSync } = require('child_process');
            const fs = require('fs');
            const path = require('path');

            // List artifacts
            const artifacts = JSON.parse(execSync('curl -s -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY/actions/artifacts').toString());

            // Find the artifact named "build-artifact"
            const artifact = artifacts.artifacts.find(artifact => artifact.name === 'build-artifact');

            // Download artifact if found
            if (artifact) {
              execSync(`curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -LJO https://api.github.com/repos/$GITHUB_REPOSITORY/actions/artifacts/${artifact.id}/zip`);
              execSync(`unzip -q ${artifact.name}.zip -d dist`);  // Extract to "dist" directory
            } else {
              throw new Error('Unable to find "build-artifact" artifact.');
            }

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
           apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
           accountId: 2c2eae7c46fdef478ca007471a296695  # Replace with your Cloudflare account ID
           projectName: demo   # Replace with your Cloudflare project name
           directory: dist  # Replace with the directory containing build artifacts
