name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create dist directory
        run: mkdir -p dist

      - name: Install dependencies and build
        run: |
          npm install
          npx gulp
          # Additional build commands if necessary

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist
          git commit -m "Add minified files"
          git push

