name: Node.js CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.14.0'

      - name: Install Tools
        run: |
          npm install uglify-js -g
          npm install gzip-js -g

      - name: Minify, Uglify and Gzip JS files
        run: |
          mkdir -p ./dist   # Create a directory to store minimized files
          for file in ./*.js; do
            base=$(basename "$file" .js)
            npx uglify-js "$file" -o "./dist/$base.min.js" --compress --mangle
            gzip -c "./dist/$base.min.js" > "./dist/$base.min.js.gz"
          done
        working-directory: ${{ github.workspace }}

      - name: Verify Output Files
        run: |
          ls -al ./dist
        working-directory: ${{ github.workspace }}
