name: Node.js CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install uglify-js
        run: npm install uglify-js -g

      - name: Run Uglify JS on all JS files
        run: |
          mkdir -p ./dist   # Create a directory to store minimized files
          for file in ./*.js; do
            npx uglify-js "$file" -o "./dist/$(basename "$file" .js).min.js" --compress --mangle
          done
        working-directory: ${{ github.workspace }}
