name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install UglifyJS and GzipJS
        run: |
          npm install uglify-js -g
          npm install gzip-js -g

      - name: Create Dist Directories
        run: |
          mkdir -p ./dist/js
          mkdir -p ./dist/html
          mkdir -p ./dist/css

      - name: Minify and Gzip JS files
        run: |
          for file in ./*.js; do
            base=$(basename "$file" .js)
            npx uglify-js "$file" -o "./dist/js/$base.min.js" --compress --mangle
            gzip -c "./dist/js/$base.min.js" > "./dist/js/$base.min.js.gz"
          done

      - name: Gzip Minified HTML files
        run: |
          for file in ./dist/html/*.html; do
            gzip -c  "./dist/js/$base.min.html" > "./dist/js/$base.min.html.gz"
          done

      - name: Minify and Gzip CSS files
        run: |
          for file in ./*.css; do
            npx clean-css-cli "$file" -o "./dist/css/$(basename $file .css).min.css"
            gzip -c "./dist/css/$(basename $file .css).min.css" > "./dist/css/$(basename $file .css).min.css.gz"
          done

      - name: Verify Output Files
        run: |
          ls -al ./dist
