name: Node.js CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Ensure Node.js and dependencies are installed
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies including uglify-js, minify, gzip-js
      - name: Install Dependencies
        run: npm ci

      # Debugging: List files to verify correct path
      - name: List Files
        run: ls -al

      # Run minification and uglification steps
      - name: Minify JS
        run: npm run minify

      - name: Uglify JS
        run: npm run uglify

      # Gzip the minified file
      - name: Gzip JS
        run: npm run gzip

      # Debugging: List files after operations to verify changes
      - name: List Files After Operations
        run: ls -al
