name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # Modify based on your branch name

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run your build steps here if required

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: YOUR_ACCOUNT_ID  # Replace with your Cloudflare account ID
          projectName: YOUR_PROJECT_NAME  # Replace with your Cloudflare project name
          directory: YOUR_BUILD_OUTPUT_DIRECTORY  # Replace with your build output directory
          # Optional: Enable this if you want GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Specify the branch to deploy to
          branch: main
          # Optional: Change the working directory
          workingDirectory: my-site
          # Optional: Change the Wrangler version, e.g., 'beta'
          wranglerVersion: '3'
